name: "l4t-ml_jp51"
run-name: "Build l4t-ml (JetPack 5.1)"
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'dev'
    paths:
      - '.github/workflows/l4t-ml_jp51.yml'
      - 'packages/l4t/l4t-ml/*'
      - '!packages/l4t/l4t-ml/README.md'
      - '!packages/l4t/l4t-ml/docs.md'
      - 'packages/build-essential/*'
      - '!packages/build-essential/README.md'
      - '!packages/build-essential/docs.md'
      - 'packages/python/*'
      - '!packages/python/README.md'
      - '!packages/python/docs.md'
      - 'packages/numpy/*'
      - '!packages/numpy/README.md'
      - '!packages/numpy/docs.md'
      - 'packages/cmake/cmake_pip/*'
      - '!packages/cmake/cmake_pip/README.md'
      - '!packages/cmake/cmake_pip/docs.md'
      - 'packages/onnx/*'
      - '!packages/onnx/README.md'
      - '!packages/onnx/docs.md'
      - 'packages/pytorch/*'
      - '!packages/pytorch/README.md'
      - '!packages/pytorch/docs.md'
      - 'packages/pytorch/torchvision/*'
      - '!packages/pytorch/torchvision/README.md'
      - '!packages/pytorch/torchvision/docs.md'
      - 'packages/pytorch/torchaudio/*'
      - '!packages/pytorch/torchaudio/README.md'
      - '!packages/pytorch/torchaudio/docs.md'
      - 'packages/protobuf/protobuf_cpp/*'
      - '!packages/protobuf/protobuf_cpp/README.md'
      - '!packages/protobuf/protobuf_cpp/docs.md'
      - 'packages/tensorflow/*'
      - '!packages/tensorflow/README.md'
      - '!packages/tensorflow/docs.md'
      - 'packages/opencv/*'
      - '!packages/opencv/README.md'
      - '!packages/opencv/docs.md'
      - 'packages/pycuda/*'
      - '!packages/pycuda/README.md'
      - '!packages/pycuda/docs.md'
      - 'packages/cupy/*'
      - '!packages/cupy/README.md'
      - '!packages/cupy/docs.md'
      - 'packages/onnxruntime/*'
      - '!packages/onnxruntime/README.md'
      - '!packages/onnxruntime/docs.md'
      - 'packages/numba/*'
      - '!packages/numba/README.md'
      - '!packages/numba/docs.md'
      - 'packages/rust/*'
      - '!packages/rust/README.md'
      - '!packages/rust/docs.md'
      - 'packages/jupyterlab/*'
      - '!packages/jupyterlab/README.md'
      - '!packages/jupyterlab/docs.md'
jobs:
  l4t-ml_jp51:
    runs-on: [self-hosted, jetson, jp51]
    steps:
      - run: |
         cat /etc/nv_tegra_release 
      - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
        run: |
         echo "$RUNNER_WORKSPACE" 
         cd $RUNNER_WORKSPACE 
         git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
         cd jetson-containers 
         git fetch origin 
         git checkout $GITHUB_SHA 
         git status 
         ls -a 
      - run: ./build.sh --name=runner/ --push=dustynv l4t-ml