name: "numba_jp46"
run-name: "Build numba (JetPack 4.6)"
on:
  workflow_dispatch: {}
  push:
    branches:
      - 'dev'
    paths:
      - '.github/workflows/numba_jp46.yml'
      - 'packages/numba/*'
      - '!packages/numba/README.md'
      - 'packages/build-essential/*'
      - '!packages/build-essential/README.md'
      - 'packages/python/*'
      - '!packages/python/README.md'
      - 'packages/numpy/*'
      - '!packages/numpy/README.md'
jobs:
  numba_jp46:
    runs-on: [self-hosted, jetson, jp46]
    steps:
      - run: |
         cat /etc/nv_tegra_release 
      - name: "Checkout ${{ github.repository }} SHA=${{ github.sha }}" 
        run: |
         echo "$RUNNER_WORKSPACE" 
         cd $RUNNER_WORKSPACE 
         git clone $GITHUB_SERVER_URL/$GITHUB_REPOSITORY || echo 'repo already cloned or another error encountered' 
         cd jetson-containers 
         git fetch origin 
         git checkout $GITHUB_SHA 
         git status 
         ls -a 
      - run: ./build.sh --name=runner/ numba